# Container for Ofertika server Ofersrv
# Agosto 2019

FROM node:8.11-alpine
LABEL maintainer="roberto.vicuna@gmail.com"

WORKDIR /usr/srv

COPY package*.json ./

RUN apk --no-cache add --virtual builds-deps build-base python p7zip

RUN apk update && apk upgrade && apk add --no-cache bash git openssh

RUN npm install

RUN npm rebuild bcrypt --build-from-source .

# no se necesita, montar directorio de fuentes en el docker-compose: COPY . . 

EXPOSE 4000

CMD ["npm", "run", "start"]



